apiVersion: elemental.cattle.io/v1beta1
kind: MachineInventorySelectorTemplate
metadata:
  name: gpu-1-nodes
  namespace: fleet-default
spec:
  template:
    spec:
      selector:
        matchExpressions:
          - key: manufacturer
            operator: In
            values:
              - NVIDIA
        matchLabels:
          manufacturer: NVIDIA
          serialNumber: '1420924215323'
